apiVersion: apps/v1
kind: Deployment
metadata:
  name: ada01-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ada01
  template:
    metadata:
      labels:
        app: ada01
    spec:
      containers:
      - name: ada01
        image: 599646583608.dkr.ecr.ap-southeast-1.amazonaws.com/dev-project/app01:v2.1
        ports:
        - containerPort: 8080