apiVersion: apps/v1
kind: Deployment
metadata:
  name: ada01-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ada01
  template:
    metadata:
      labels:
        app: ada01
    spec:
      containers:
      - name: ada-a
        image: 599646583608.dkr.ecr.ap-southeast-1.amazonaws.com/ada01/service-a:v2.4
        ports:
        - containerPort: 5000