apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: ada-a
        image: 599646583608.dkr.ecr.ap-southeast-1.amazonaws.com/ada01/service-a:v2.3
        ports:
        - containerPort: 5000